In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

## ***Importing Data***

In [7]:
from google.colab import drive

#'https://drive.google.com/file/d/1I2CYwSv3nt9bTGsTqm-8Su9n-2sadG5q/view?usp=drive_link'
url = 'https://drive.google.com/file/d/1I2CYwSv3nt9bTGsTqm-8Su9n-2sadG5q/view?usp=drive_link'
file_id = url.split('/')[-2]
drive = 'https://drive.google.com/uc?id=' + file_id
data = pd.read_csv(drive)
data

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0          0.0            0.0                 1.0           0       0   
1          0.0            0.0                 1.0           0       0   
2          0.0            0.0                 0.0           0       0   
3          0.0            0.0                 0.0           0       0   
4          0.0            0.0                 0.0           0       0   
...        ...            ...                 ...         ...     ...   
4995       0.0            0.0                 0.0           0       1   
4996      85.0            0.0                 0.0           0       1   
4997       0.0            0.0                 0.0           0       0   
4998       0.0            0.0                 0.0           0       1   
4999       0.0            0.0                 0.0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [8]:
data.isna().sum()


ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              2
Personal Loan         1
Securities Account    1
CD Account            0
Online                0
CreditCard            0
dtype: int64

### ***Data Pre-processing***

In [9]:
data['Mortgage'] = data['Mortgage'].fillna(data['Mortgage'].mean())
data['Personal Loan'] = data['Personal Loan'].fillna(data['Personal Loan'].mean())
data['Securities Account'] = data['Securities Account'].fillna(data['Securities Account'].mean())

data.isna().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [33]:
# Encoding categorical data

data = data.drop('ID',axis=1)

x = data.drop('CreditCard', axis =1)
y = data['CreditCard']

print("The independent variable X are",x)

print("The independent variable X are",y)


The independent variable X are       Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0      25           1      49     91107       4    1.6          1       0.0   
1      45          19      34     90089       3    1.5          1       0.0   
2      39          15      11     94720       1    1.0          1       0.0   
3      35           9     100     94112       1    2.7          2       0.0   
4      35           8      45     91330       4    1.0          2       0.0   
...   ...         ...     ...       ...     ...    ...        ...       ...   
4995   29           3      40     92697       1    1.9          3       0.0   
4996   30           4      15     92037       4    0.4          1      85.0   
4997   63          39      24     93023       2    0.3          3       0.0   
4998   65          40      49     90034       3    0.5          2       0.0   
4999   28           4      83     92612       3    0.8          1       0.0   

      Personal Loan 

In [36]:
x.head()


Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   25           1      49     91107       4    1.6          1       0.0   
1   45          19      34     90089       3    1.5          1       0.0   
2   39          15      11     94720       1    1.0          1       0.0   
3   35           9     100     94112       1    2.7          2       0.0   
4   35           8      45     91330       4    1.0          2       0.0   

   Personal Loan  Securities Account  CD Account  Online  
0            0.0                 1.0           0       0  
1            0.0                 1.0           0       0  
2            0.0                 0.0           0       0  
3            0.0                 0.0           0       0  
4            0.0                 0.0           0       0

In [37]:
y.head()

0    0
1    0
2    0
3    0
4    1
Name: CreditCard, dtype: int64

### ***Model Training***

In [65]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4,random_state= None)

print("x train:\n",x_train)
print("x test:\n",x_test)
print("y train:\n",y_train)
print("y test:\n",y_test)

x train:
       Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
468    34          10      21     92634       1    0.5          3       0.0   
1891   42          18      50     95126       4    2.2          2       0.0   
1395   47          23     190     92831       4    0.3          3     305.0   
3068   56          26      90     92120       2    4.5          3       0.0   
745    30           4      49     93955       3    1.1          2       0.0   
...   ...         ...     ...       ...     ...    ...        ...       ...   
2997   57          33      80     95053       4    1.6          2       0.0   
2471   36          11      44     91040       2    1.1          2      85.0   
4338   54          30     121     92121       2    0.4          1       0.0   
4111   43          17      21     95351       3    1.5          1       0.0   
1017   31           5      40     94305       4    1.3          3     170.0   

      Personal Loan  Securities Account  

In [66]:
from sklearn.preprocessing import StandardScaler
ssc = StandardScaler()
x_train = ssc.fit_transform(x_train)
x_test = ssc.transform(x_test)

In [67]:
from sklearn.svm import SVC
model = SVC(kernel='rbf',random_state=None)
model.fit(x_train, y_train)

SVC()

In [68]:
model.intercept_

array([-0.44381972])

In [69]:
model.n_support_

array([1068,  797], dtype=int32)

In [70]:
model.support_vectors_

array([[ 0.12832172,  0.23511812,  2.54782547, ..., -0.34807905,
        -0.26148818, -1.20789751],
       [ 0.90707793,  0.49507674,  0.37438275, ..., -0.34807905,
        -0.26148818, -1.20789751],
       [ 1.68583414,  1.62156407, -1.10355829, ..., -0.34807905,
        -0.26148818, -1.20789751],
       ...,
       [ 0.47443559,  0.49507674, -1.32090257, ..., -0.34807905,
        -0.26148818,  0.82788481],
       [-0.13126369, -0.02484049,  1.67844838, ..., -0.34807905,
        -0.26148818, -1.20789751],
       [-0.21779215, -0.11149336,  0.8090713 , ..., -0.34807905,
        -0.26148818, -1.20789751]])

In [71]:
y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score

Cm_train = confusion_matrix(y_train, y_pred_train)
print(Cm_train)

Cm_test = confusion_matrix(y_test, y_pred_test)
print(Cm_test)

[[2109   15]
 [ 726  150]]
[[1392   14]
 [ 516   78]]


### ***Accuracy Test***

In [81]:
accuracy_train = accuracy_score(y_train, y_pred_train)
print("Accuracy:",(accuracy_train)*100, '%')

Accuracy: 75.3 %


In [83]:
accuracy_test = accuracy_score(y_test, y_pred_test)
print((accuracy_test)*100, '%')

73.5 %


In [84]:
from sklearn.metrics import classification_report

# Additional performance metrics
report_train = classification_report(y_train, y_pred_train)
report_test = classification_report(y_test, y_pred_test)

print("Training Set Metrics:")
print(report_train)

print("Testing Set Metrics:")
print(report_test)

# Feature weights (coefficients) for linear kernel
if model.kernel == 'linear':
    feature_weights = model.coef_
    print("Feature Weights:")
    print(feature_weights)

Training Set Metrics:
              precision    recall  f1-score   support

           0       0.74      0.99      0.85      2124
           1       0.91      0.17      0.29       876

    accuracy                           0.75      3000
   macro avg       0.83      0.58      0.57      3000
weighted avg       0.79      0.75      0.69      3000

Testing Set Metrics:
              precision    recall  f1-score   support

           0       0.73      0.99      0.84      1406
           1       0.85      0.13      0.23       594

    accuracy                           0.73      2000
   macro avg       0.79      0.56      0.53      2000
weighted avg       0.76      0.73      0.66      2000



In [85]:
Predicted = model.predict(x_test)

In [86]:
df = {'Predicted': Predicted, 'Actual': y_test}
pd.DataFrame(df)

Predicted  Actual
360           0       0
3691          0       1
2458          0       1
416           0       0
4904          0       1
...         ...     ...
1799          0       0
4464          0       1
2058          0       0
4             0       1
1526          0       0

[2000 rows x 2 columns]

In [87]:
import joblib

# Save the trained SVM model to a file
joblib.dump(model, 'svm_model.pkl')

# Save the StandardScaler object to a file
joblib.dump(ssc, 'scaler.pkl')

['scaler.pkl']